

- EXAMPLE OF REPORT WE'D LIKE TO SEE DURING THE PRESENTATION ... 
- Provision laptops ... and validate the execution.
- test curl on laptops..  ask karsten to test. 

- provide slides / tools etc.. 


set the remoteworkinterval to 0.2
repeat 5 times 
	Run "DAI/home".menuOptions ("Electronics"),("Camera & Phones")
	Run "DAI/itemsPage".selectItem
	
	Run "DAI/itemPage".validate
end repeat 

repeat 5 times 
	Run "DAI/home".menuOptions ("Computers"),("Desktops & Notebooks")
	Run "DAI/itemsPage".selectItem
	
	Run "DAI/itemPage".validate
end repeat

repeat 5 times 
	Run "DAI/home".menuOptions ("Computers"),("Digital Solutions")
	Run "DAI/itemsPage".selectItem
	
	Run "DAI/itemPage".validate
end repeat

repeat 5 times 
	Run "DAI/home".menuOptions ("Books"),("Fiction")
	Run "DAI/itemsPage".selectItem
	
	Run "DAI/itemPage".validate
end repeat

repeat 5 times 
	Run "DAI/home".menuOptions ("Books"),("Non Fiction")
	Run "DAI/itemsPage".selectItem
	
	Run "DAI/itemPage".validate
end repeat













log remoteclipboard()


to fetchApiTest product
	put get() into t 
	--log JSONVALUE(t.responseBody)
	put each item of JSONVALUE(t.responseBody) whose "name" is product into global product
	
end fetchApiTest

- 1 Works
- 2 Works
- 3 Not sure
- 4 OOS
- 5 Not Working
- 6 Works
- 7 Works
- 8 Maybe update the price of the item.
- 9 Not sure 
- 10 Works

// Bug 1. 
main.launchBrowser ("https://nopcommerce.eggplantlab.com/samsung-series-9-np900x4c-premium-ultrabook") -- how can this work if its a redirect for 10 

// Bug 2  -- Not in scope any more 
main.launchBrowser ("https://nopcommerce.eggplantlab.com/adobe-photoshop-cs4")

// Bug 3  --  Not working 
main.launchBrowser ("https://nopcommerce.eggplantlab.com/romeo-and-juliet-wordsworth-collectors-editions")

// Bug 4 
-- Works but is out of scope ? 

// Bug 5  -- does not work 
main.launchBrowser ("https://nopcommerce.eggplantlab.com/asus-n551jk-xo076h-laptop")

// Bug 6  ---------------------
// Iphone 15
main.launchBrowser ("https://nopcommerce.eggplantlab.com/iphone-15")
fetchApiTest ("Iphone 15") 
Run "DAI/itemPage".validate 

//  Samsung 
main.launchBrowser ("https://nopcommerce.eggplantlab.com/samsung-series-9-np900x4c-premium-ultrabook")
fetchApiTest ("Samsung Series 9 NP900X4C Premium Ultrabook") 
Run "DAI/itemPage".validate 

// APPLE Apple MacBook Pro 13-inch 
main.launchBrowser ("https://nopcommerce.eggplantlab.com/apple-macbook-pro-13-inch")
fetchApiTest ("Apple MacBook Pro 13-inch/") 
Run "DAI/itemPage".validate 


// Bug for rating (try)
// Bug for availability (Instock but API says out of stock )
// Bug for SKU 
// Bug for Price 



// BUG 7  -- WORKS
main.launchBrowser ("https://nopcommerce.eggplantlab.com/register")
Run "DAI/register".registerUser

// BUG 8  -- wrong total - not basket total 

-- Maybe remove filter and change for someting else 
// BUG 9 Jewelery not in scope any more 
main.launchBrowser ("https://nopcommerce.eggplantlab.com/books")


// BUG 10  -- Not working 
main.launchBrowser ("https://nopcommerce.eggplantlab.com/digital-storm-vanquish-3-custom-performance-pc") -- still works
main.launchBrowser ("https://nopcommerce.eggplantlab.com/asus-n551jk-xo076h-laptop") -- still works
